trigger: none

pool: cicdpool  

stages:
- stage: scanningtools
  jobs:
  - job: gitleaks
    steps: 
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Running Gitleaks secret scan..."
          
                gitleaks detect `
                  --source . `
                  --config env/dev/.gitleaks.toml `
                  --verbose `
                  --redact `
                  --exit-code 1
          
                if ($LASTEXITCODE -ne 0) {
                    Write-Host "##vso[task.logissue type=error]Gitleaks detected a secret!"
                    Write-Host "##vso[task.complete result=Failed;]Gitleaks Secret Scan Failed"
                    exit 1
                }
          
                Write-Host "Gitleaks scan passed successfully."

- stage: initandplan
  jobs:
  - job: init
    steps: 
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
        backendServiceArm: 'cicdinfra_sc'
        backendAzureRmStorageAccountName: 'terraformstatefile55'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.terraform.state'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
        environmentServiceNameAzureRM: 'cicdinfra_sc'


# - stage: manualvlidation
#   pool: server
#   jobs:
#   - job: manualvalidate
#     steps:
#     - task: ManualValidation@1
#       inputs:
#         notifyUsers: 'manoj@nevalosstechnologies.com'
#         approvers: 'manoj@nevalosstechnologies.com'

# - stage: initandapply
#   jobs:
#   - job: init
#     steps: 
#     - task: TerraformTask@5
#       inputs:
#         provider: 'azurerm'
#         command: 'init'
#         workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
#         backendServiceArm: 'cicdinfra_sc'
#         backendAzureRmStorageAccountName: 'terraformstatefile55'
#         backendAzureRmContainerName: 'tfstate'
#         backendAzureRmKey: 'dev.terraform.state'

#     - task: TerraformTask@5
#       inputs:
#         provider: 'azurerm'
#         command: 'destroy'
#         workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
#         commandOptions: '-auto-approve'
#         environmentServiceNameAzureRM: 'cicdinfra_sc'
