trigger: none

pool: cicdpool  

stages:
- stage: initandplan
  jobs:
  - job: init
    steps: 
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
        backendServiceArm: 'cicdinfra_sc'
        backendAzureRmStorageAccountName: 'terraformstatefile55'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
        backendServiceArm: 'cicdinfra_sc'
        backendAzureRmStorageAccountName: 'terraformstatefile55'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.tfstate'  